#ifndef KERNEL_TEST_TIMER_DRIVER_TEST_TIMERDRIVER_TEST_H_
#define KERNEL_TEST_TIMER_DRIVER_TEST_TIMERDRIVER_TEST_H_

void test_timerdriver(void);

#endif /* KERNEL_TEST_TIMER_DRIVER_TEST_TIMERDRIVER_TEST_H_ */
