#ifndef KERNEL_DRIVERS_TIMER_DRIVER_TIMER_MODES_H_
#define KERNEL_DRIVERS_TIMER_DRIVER_TIMER_MODES_H_

typedef enum mode{
    CAPTURE, COMPARE, OVERFLOW
}timer_mode_t;

#endif /* KERNEL_DRIVERS_TIMER_DRIVER_TIMER_MODES_H_ */
