#ifndef KERNEL_TEST_UART_DRIVER_TEST_UARTDRIVER_TEST_H_
#define KERNEL_TEST_UART_DRIVER_TEST_UARTDRIVER_TEST_H_

void test_uartdriver(void);

#endif /* KERNEL_TEST_UART_DRIVER_TEST_UARTDRIVER_TEST_H_ */
