#ifndef SRC_DRIVERS_HAL_INCLUDES_PW_REGISTER_H_
#define SRC_DRIVERS_HAL_INCLUDES_PW_REGISTER_H_

#include <inttypes.h>

#define PM_PWSTCTRL_PER     0x483070E0


#endif /* SRC_DRIVERS_HAL_INCLUDES_PW_REGISTER_H_ */
